# Generated by Django 4.1.1 on 2022-09-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClubUser',
            new_name='JDEVUser',
        ),
    ]
