# Generated by Django 4.1.1 on 2022-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_myclubuser_jdevuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='web',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zip_code',
        ),
    ]
