# Generated by Django 4.1.1 on 2022-09-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_attendees_remove_venue_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jdevuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.jdevuser'),
        ),
        migrations.AlterField(
            model_name='jdevuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
