# Generated by Django 4.1.1 on 2022-09-16 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_event_jdevuser_alter_jdevuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdevuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jdevuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='Bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='Organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jdevuser',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
