# Generated by Django 4.1.1 on 2022-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_jdevuser_first_name_remove_jdevuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdevuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='jdevuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
