# Generated by Django 4.1.1 on 2022-09-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_first_name_jdevuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdevuser',
            old_name='Organization',
            new_name='Branch',
        ),
    ]
