# Generated by Django 4.1.1 on 2022-09-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_attendees_remove_venue_address_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Organization', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('YES', 'YES'), ('MAYBE', 'MAYBE'), ('NO', 'NO')], default='NO', max_length=200, null=True)),
                ('count', models.IntegerField(null=True)),
                ('event_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('jdevUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.jdevuser')),
            ],
        ),
    ]
