# Generated by Django 4.1.1 on 2022-09-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='jdevUser',
            new_name='jdevuser',
        ),
    ]
