# Generated by Django 4.1.1 on 2022-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_jdevuser_register_jdevuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisteration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
